# Generated by Django 6.0.3 on 2026-03-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_position',
            field=models.CharField(default='center', help_text="CSS object-position (e.g., 'top', 'center', 'center 20%')", max_length=50),
        ),
    ]
